import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { sanityClient, urlFor } from '../lib/sanity';
import Link from 'next/link';
import { Recipe } from '../models/recipe';

const recipesQuery = `
*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`

const UnorderList = ({ recipes }: { recipes: Recipe[] }) => {
  return (
    <ul className="recipes-list">
      {recipes?.length > 0 && recipes.map((recipe) => (
        <li key={recipe._id} className="recipe-card">
          <Link href={`/recipes/${recipe.slug.current}`}>
            <a>
              <img src={urlFor(recipe.mainImage).url()} alt={recipe.name} />
              <span>{recipe.name}</span>
            </a>
          </Link>
        </li>
      ))}
    </ul>
  )
}

const Home: NextPage = (props) => {
  const { recipes } = props as { recipes: Recipe[] }
  return (
    <div className={styles.container}>
      <Head>
        <title>Kap's Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Kap's Kitchen</h1>
      <UnorderList recipes={recipes} />
    </div>
  )
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: {
      recipes
    }
  };
}

export default Home
